-- PostgreSQL 15+ normalized appointment module schema
CREATE TYPE appointment_mode AS ENUM ('clinic','video','audio','home_visit');
CREATE TYPE appointment_priority AS ENUM ('routine','urgent','emergency');
CREATE TYPE appointment_state AS ENUM ('booked','checked_in','vitals_pending','waiting','in_consultation','completed','cancelled','no_show','payment_pending');
CREATE TABLE providers (id uuid PRIMARY KEY, user_id uuid UNIQUE NOT NULL, provider_kind text NOT NULL CHECK (provider_kind IN ('doctor','dietician')), display_name text NOT NULL, department text, active boolean NOT NULL DEFAULT true);
CREATE TABLE appointment_types (id smallserial PRIMARY KEY, name text UNIQUE NOT NULL, provider_kind text, duration_minutes smallint NOT NULL CHECK(duration_minutes BETWEEN 5 AND 240), default_fee numeric(12,2) NOT NULL DEFAULT 0);
CREATE TABLE appointment_status (code appointment_state PRIMARY KEY, label text NOT NULL, display_order smallint NOT NULL);
CREATE TABLE appointments (id uuid PRIMARY KEY, clinic_id uuid NOT NULL, patient_id uuid NOT NULL, provider_id uuid NOT NULL REFERENCES providers(id), appointment_type_id smallint NOT NULL REFERENCES appointment_types(id), starts_at timestamptz NOT NULL, ends_at timestamptz NOT NULL, mode appointment_mode NOT NULL, priority appointment_priority NOT NULL DEFAULT 'routine', status appointment_state NOT NULL DEFAULT 'booked', reason text, fee numeric(12,2), created_by uuid NOT NULL, created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now(), CHECK(ends_at > starts_at));
CREATE INDEX appointments_provider_time_idx ON appointments(provider_id, starts_at); CREATE INDEX appointments_patient_time_idx ON appointments(patient_id, starts_at DESC);
CREATE TABLE provider_schedule (id uuid PRIMARY KEY, provider_id uuid NOT NULL REFERENCES providers(id), weekday smallint NOT NULL CHECK(weekday BETWEEN 0 AND 6), morning_start time, morning_end time, evening_start time, evening_end time, slot_minutes smallint NOT NULL, break_start time, break_end time, max_patients smallint, emergency_buffer_minutes smallint NOT NULL DEFAULT 0);
CREATE TABLE provider_leave (id uuid PRIMARY KEY, provider_id uuid NOT NULL REFERENCES providers(id), starts_on date NOT NULL, ends_on date NOT NULL, reason text, CHECK(ends_on >= starts_on));
CREATE TABLE time_slots (id uuid PRIMARY KEY, provider_id uuid NOT NULL REFERENCES providers(id), starts_at timestamptz NOT NULL, ends_at timestamptz NOT NULL, capacity smallint NOT NULL DEFAULT 1, reserved_count smallint NOT NULL DEFAULT 0, state text NOT NULL CHECK(state IN ('available','booked','blocked','lunch','leave')), UNIQUE(provider_id, starts_at));
CREATE TABLE queues (id uuid PRIMARY KEY, clinic_id uuid NOT NULL, provider_id uuid REFERENCES providers(id), queue_date date NOT NULL, queue_kind text NOT NULL CHECK(queue_kind IN ('doctor','dietician','teleconsultation')), current_token integer, UNIQUE(clinic_id,provider_id,queue_date,queue_kind));
CREATE TABLE tokens (id uuid PRIMARY KEY, queue_id uuid NOT NULL REFERENCES queues(id), appointment_id uuid UNIQUE NOT NULL REFERENCES appointments(id), token_number integer NOT NULL, checked_in_at timestamptz, called_at timestamptz, completed_at timestamptz, UNIQUE(queue_id,token_number));
CREATE TABLE vitals (id uuid PRIMARY KEY, appointment_id uuid UNIQUE NOT NULL REFERENCES appointments(id), height_cm numeric(5,1), weight_kg numeric(5,1), bmi numeric(4,1), waist_cm numeric(5,1), hip_cm numeric(5,1), temperature_c numeric(4,1), pulse_bpm smallint, respiratory_rate smallint, systolic_bp smallint, diastolic_bp smallint, spo2 smallint, rbs_mg_dl smallint, pain_score smallint CHECK(pain_score BETWEEN 0 AND 10), smoking text, alcohol text, exercise text, sleep_hours numeric(3,1), pregnancy_status text, recorded_by uuid NOT NULL, recorded_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE followups (id uuid PRIMARY KEY, parent_appointment_id uuid NOT NULL REFERENCES appointments(id), followup_appointment_id uuid REFERENCES appointments(id), suggested_days smallint NOT NULL, clinical_reason text, created_by uuid NOT NULL, created_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE teleconsultations (id uuid PRIMARY KEY, appointment_id uuid UNIQUE NOT NULL REFERENCES appointments(id), meeting_url text, provider_room_id text, meeting_status text NOT NULL CHECK(meeting_status IN ('waiting','joined','completed','missed','cancelled')), joined_at timestamptz, ended_at timestamptz);
CREATE TABLE appointment_logs (id bigserial PRIMARY KEY, appointment_id uuid NOT NULL REFERENCES appointments(id), actor_id uuid NOT NULL, event_type text NOT NULL, before_state jsonb, after_state jsonb, occurred_at timestamptz NOT NULL DEFAULT now());
-- Enforce non-overlap at the database level (requires btree_gist)
CREATE EXTENSION IF NOT EXISTS btree_gist; ALTER TABLE appointments ADD CONSTRAINT provider_appointment_no_overlap EXCLUDE USING gist (provider_id WITH =, tstzrange(starts_at, ends_at, '[)') WITH &&) WHERE (status NOT IN ('cancelled','no_show'));
